#object files, directories for this test
OBJS=main.o
LIBS=../../ALib/libsharedptr.a
DIRS=.. ../../sharedptr

#executable name
EXEFILE=../../ABin/sharedptr

#all other makefile lines
include ../../maketests
